name: Build cloudsploit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ opened, synchronize, reopened ]

jobs:
  build-cloudsploit:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: cloudsploit/package.json
        
    - run: npm install --prefix cloudsploit

    - run: node cloudsploit/index.js --help